<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit898b3067ea305b7ed4b2c5c80885f4d6
{
    public static $prefixLengthsPsr4 = array (
        'B' => 
        array (
            'BigBlueButton\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'BigBlueButton\\' => 
        array (
            0 => __DIR__ . '/..' . '/src',
        ),
    );

    public static $classMap = array (
        'BigBlueButton\\BigBlueButton' => __DIR__ . '/..' . '/src/BigBlueButton.php',
        'BigBlueButton\\Core\\ApiMethod' => __DIR__ . '/..' . '/src/Core/ApiMethod.php',
        'BigBlueButton\\Core\\Attendee' => __DIR__ . '/..' . '/src/Core/Attendee.php',
        'BigBlueButton\\Core\\Hook' => __DIR__ . '/..' . '/src/Core/Hook.php',
        'BigBlueButton\\Core\\Meeting' => __DIR__ . '/..' . '/src/Core/Meeting.php',
        'BigBlueButton\\Core\\Record' => __DIR__ . '/..' . '/src/Core/Record.php',
        'BigBlueButton\\Parameters\\BaseParameters' => __DIR__ . '/..' . '/src/Parameters/BaseParameters.php',
        'BigBlueButton\\Parameters\\CreateMeetingParameters' => __DIR__ . '/..' . '/src/Parameters/CreateMeetingParameters.php',
        'BigBlueButton\\Parameters\\DeleteRecordingsParameters' => __DIR__ . '/..' . '/src/Parameters/DeleteRecordingsParameters.php',
        'BigBlueButton\\Parameters\\EndMeetingParameters' => __DIR__ . '/..' . '/src/Parameters/EndMeetingParameters.php',
        'BigBlueButton\\Parameters\\GetMeetingInfoParameters' => __DIR__ . '/..' . '/src/Parameters/GetMeetingInfoParameters.php',
        'BigBlueButton\\Parameters\\GetRecordingsParameters' => __DIR__ . '/..' . '/src/Parameters/GetRecordingsParameters.php',
        'BigBlueButton\\Parameters\\HooksCreateParameters' => __DIR__ . '/..' . '/src/Parameters/HooksCreateParameters.php',
        'BigBlueButton\\Parameters\\HooksDestroyParameters' => __DIR__ . '/..' . '/src/Parameters/HooksDestroyParameters.php',
        'BigBlueButton\\Parameters\\IsMeetingRunningParameters' => __DIR__ . '/..' . '/src/Parameters/IsMeetingRunningParameters.php',
        'BigBlueButton\\Parameters\\JoinMeetingParameters' => __DIR__ . '/..' . '/src/Parameters/JoinMeetingParameters.php',
        'BigBlueButton\\Parameters\\MetaParameters' => __DIR__ . '/..' . '/src/Parameters/MetaParameters.php',
        'BigBlueButton\\Parameters\\PublishRecordingsParameters' => __DIR__ . '/..' . '/src/Parameters/PublishRecordingsParameters.php',
        'BigBlueButton\\Parameters\\SetConfigXMLParameters' => __DIR__ . '/..' . '/src/Parameters/SetConfigXMLParameters.php',
        'BigBlueButton\\Parameters\\UpdateRecordingsParameters' => __DIR__ . '/..' . '/src/Parameters/UpdateRecordingsParameters.php',
        'BigBlueButton\\Parameters\\UserDataParameters' => __DIR__ . '/..' . '/src/Parameters/UserDataParameters.php',
        'BigBlueButton\\Responses\\ApiVersionResponse' => __DIR__ . '/..' . '/src/Responses/ApiVersionResponse.php',
        'BigBlueButton\\Responses\\BaseResponse' => __DIR__ . '/..' . '/src/Responses/BaseResponse.php',
        'BigBlueButton\\Responses\\CreateMeetingResponse' => __DIR__ . '/..' . '/src/Responses/CreateMeetingResponse.php',
        'BigBlueButton\\Responses\\DeleteRecordingsResponse' => __DIR__ . '/..' . '/src/Responses/DeleteRecordingsResponse.php',
        'BigBlueButton\\Responses\\EndMeetingResponse' => __DIR__ . '/..' . '/src/Responses/EndMeetingResponse.php',
        'BigBlueButton\\Responses\\GetDefaultConfigXMLResponse' => __DIR__ . '/..' . '/src/Responses/GetDefaultConfigXMLResponse.php',
        'BigBlueButton\\Responses\\GetMeetingInfoResponse' => __DIR__ . '/..' . '/src/Responses/GetMeetingInfoResponse.php',
        'BigBlueButton\\Responses\\GetMeetingsResponse' => __DIR__ . '/..' . '/src/Responses/GetMeetingsResponse.php',
        'BigBlueButton\\Responses\\GetRecordingsResponse' => __DIR__ . '/..' . '/src/Responses/GetRecordingsResponse.php',
        'BigBlueButton\\Responses\\HooksCreateResponse' => __DIR__ . '/..' . '/src/Responses/HooksCreateResponse.php',
        'BigBlueButton\\Responses\\HooksDestroyResponse' => __DIR__ . '/..' . '/src/Responses/HooksDestroyResponse.php',
        'BigBlueButton\\Responses\\HooksListResponse' => __DIR__ . '/..' . '/src/Responses/HooksListResponse.php',
        'BigBlueButton\\Responses\\IsMeetingRunningResponse' => __DIR__ . '/..' . '/src/Responses/IsMeetingRunningResponse.php',
        'BigBlueButton\\Responses\\JoinMeetingResponse' => __DIR__ . '/..' . '/src/Responses/JoinMeetingResponse.php',
        'BigBlueButton\\Responses\\PublishRecordingsResponse' => __DIR__ . '/..' . '/src/Responses/PublishRecordingsResponse.php',
        'BigBlueButton\\Responses\\SetConfigXMLResponse' => __DIR__ . '/..' . '/src/Responses/SetConfigXMLResponse.php',
        'BigBlueButton\\Responses\\UpdateRecordingsResponse' => __DIR__ . '/..' . '/src/Responses/UpdateRecordingsResponse.php',
        'BigBlueButton\\Util\\UrlBuilder' => __DIR__ . '/..' . '/src/Util/UrlBuilder.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit898b3067ea305b7ed4b2c5c80885f4d6::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit898b3067ea305b7ed4b2c5c80885f4d6::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit898b3067ea305b7ed4b2c5c80885f4d6::$classMap;

        }, null, ClassLoader::class);
    }
}
