<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'BigBlueButton\\BigBlueButton' => $vendorDir . '/src/BigBlueButton.php',
    'BigBlueButton\\Core\\ApiMethod' => $vendorDir . '/src/Core/ApiMethod.php',
    'BigBlueButton\\Core\\Attendee' => $vendorDir . '/src/Core/Attendee.php',
    'BigBlueButton\\Core\\Hook' => $vendorDir . '/src/Core/Hook.php',
    'BigBlueButton\\Core\\Meeting' => $vendorDir . '/src/Core/Meeting.php',
    'BigBlueButton\\Core\\Record' => $vendorDir . '/src/Core/Record.php',
    'BigBlueButton\\Parameters\\BaseParameters' => $vendorDir . '/src/Parameters/BaseParameters.php',
    'BigBlueButton\\Parameters\\CreateMeetingParameters' => $vendorDir . '/src/Parameters/CreateMeetingParameters.php',
    'BigBlueButton\\Parameters\\DeleteRecordingsParameters' => $vendorDir . '/src/Parameters/DeleteRecordingsParameters.php',
    'BigBlueButton\\Parameters\\EndMeetingParameters' => $vendorDir . '/src/Parameters/EndMeetingParameters.php',
    'BigBlueButton\\Parameters\\GetMeetingInfoParameters' => $vendorDir . '/src/Parameters/GetMeetingInfoParameters.php',
    'BigBlueButton\\Parameters\\GetRecordingsParameters' => $vendorDir . '/src/Parameters/GetRecordingsParameters.php',
    'BigBlueButton\\Parameters\\HooksCreateParameters' => $vendorDir . '/src/Parameters/HooksCreateParameters.php',
    'BigBlueButton\\Parameters\\HooksDestroyParameters' => $vendorDir . '/src/Parameters/HooksDestroyParameters.php',
    'BigBlueButton\\Parameters\\IsMeetingRunningParameters' => $vendorDir . '/src/Parameters/IsMeetingRunningParameters.php',
    'BigBlueButton\\Parameters\\JoinMeetingParameters' => $vendorDir . '/src/Parameters/JoinMeetingParameters.php',
    'BigBlueButton\\Parameters\\MetaParameters' => $vendorDir . '/src/Parameters/MetaParameters.php',
    'BigBlueButton\\Parameters\\PublishRecordingsParameters' => $vendorDir . '/src/Parameters/PublishRecordingsParameters.php',
    'BigBlueButton\\Parameters\\SetConfigXMLParameters' => $vendorDir . '/src/Parameters/SetConfigXMLParameters.php',
    'BigBlueButton\\Parameters\\UpdateRecordingsParameters' => $vendorDir . '/src/Parameters/UpdateRecordingsParameters.php',
    'BigBlueButton\\Parameters\\UserDataParameters' => $vendorDir . '/src/Parameters/UserDataParameters.php',
    'BigBlueButton\\Responses\\ApiVersionResponse' => $vendorDir . '/src/Responses/ApiVersionResponse.php',
    'BigBlueButton\\Responses\\BaseResponse' => $vendorDir . '/src/Responses/BaseResponse.php',
    'BigBlueButton\\Responses\\CreateMeetingResponse' => $vendorDir . '/src/Responses/CreateMeetingResponse.php',
    'BigBlueButton\\Responses\\DeleteRecordingsResponse' => $vendorDir . '/src/Responses/DeleteRecordingsResponse.php',
    'BigBlueButton\\Responses\\EndMeetingResponse' => $vendorDir . '/src/Responses/EndMeetingResponse.php',
    'BigBlueButton\\Responses\\GetDefaultConfigXMLResponse' => $vendorDir . '/src/Responses/GetDefaultConfigXMLResponse.php',
    'BigBlueButton\\Responses\\GetMeetingInfoResponse' => $vendorDir . '/src/Responses/GetMeetingInfoResponse.php',
    'BigBlueButton\\Responses\\GetMeetingsResponse' => $vendorDir . '/src/Responses/GetMeetingsResponse.php',
    'BigBlueButton\\Responses\\GetRecordingsResponse' => $vendorDir . '/src/Responses/GetRecordingsResponse.php',
    'BigBlueButton\\Responses\\HooksCreateResponse' => $vendorDir . '/src/Responses/HooksCreateResponse.php',
    'BigBlueButton\\Responses\\HooksDestroyResponse' => $vendorDir . '/src/Responses/HooksDestroyResponse.php',
    'BigBlueButton\\Responses\\HooksListResponse' => $vendorDir . '/src/Responses/HooksListResponse.php',
    'BigBlueButton\\Responses\\IsMeetingRunningResponse' => $vendorDir . '/src/Responses/IsMeetingRunningResponse.php',
    'BigBlueButton\\Responses\\JoinMeetingResponse' => $vendorDir . '/src/Responses/JoinMeetingResponse.php',
    'BigBlueButton\\Responses\\PublishRecordingsResponse' => $vendorDir . '/src/Responses/PublishRecordingsResponse.php',
    'BigBlueButton\\Responses\\SetConfigXMLResponse' => $vendorDir . '/src/Responses/SetConfigXMLResponse.php',
    'BigBlueButton\\Responses\\UpdateRecordingsResponse' => $vendorDir . '/src/Responses/UpdateRecordingsResponse.php',
    'BigBlueButton\\Util\\UrlBuilder' => $vendorDir . '/src/Util/UrlBuilder.php',
);
